"""Configuration models for TestBench Requirement Service."""

from pathlib import Path

from pydantic import BaseModel, Field, field_validator

from testbench_requirement_service.models.logging import LoggingConfig

DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 8020


class RequirementServiceConfig(BaseModel):
    """Validated service config loaded from TOML config file."""

    reader_class: str = Field(
        "testbench_requirement_service.readers.JsonlRequirementReader",
        description="Class path of the active requirement reader",
    )
    reader_config_path: Path | None = Field(
        default=None,
        description="Optional path to a separate reader configuration file",
    )
    host: str = Field(
        DEFAULT_HOST,
        description="Hostname or IP address to bind the service to",
    )
    port: int = Field(
        DEFAULT_PORT,
        description="Port number to bind the service to",
    )
    debug: bool = Field(False, description="Enable debug mode for the service")
    password_hash: str | None = Field(
        default=None,
        description="Hashed admin password generated by the configuration wizard",
    )
    salt: str | None = Field(
        default=None,
        description="Base64-encoded salt stored alongside the password hash",
    )
    logging: LoggingConfig = Field(
        default_factory=LoggingConfig,
        description="Structured logging configuration for the service runtime",
    )
    reader_config: dict = Field(
        default_factory=dict,
        description="Inline reader configuration when no separate file is used",
    )
    ssl_cert: Path | None = Field(
        default=None,
        description="Path to SSL/TLS certificate file for HTTPS support (.crt or .pem)",
    )
    ssl_key: Path | None = Field(
        default=None,
        description="Path to SSL/TLS private key file for HTTPS support (.key)",
    )
    ssl_ca_cert: Path | None = Field(
        default=None,
        description="Optional path to CA certificate file for client verification",
    )
    proxies_count: int | None = Field(
        default=None,
        description="Number of proxy servers in front of the application (for X-Forwarded headers)",
    )
    real_ip_header: str | None = Field(
        default=None,
        description="Header name to use for client IP (e.g., 'X-Real-IP')",
    )
    forwarded_secret: str | None = Field(
        default=None,
        description="Secret token for validating Forwarded header (security measure)",
    )

    @field_validator("reader_config_path")
    @classmethod
    def validate_reader_config_exists(cls, v: Path | None) -> Path | None:
        """Validate that reader_config_path exists if provided."""
        if v is not None and not v.exists():
            raise ValueError(f"Reader config file not found: '{v}'")
        return v

    @field_validator("ssl_cert", "ssl_key", "ssl_ca_cert")
    @classmethod
    def validate_ssl_files_exist(cls, v: Path | None) -> Path | None:
        """Validate that SSL certificate files exist if provided."""
        if v is not None and not v.exists():
            raise ValueError(f"SSL certificate file not found: '{v}'")
        return v
